<?php

namespace Osimatic\Bank;

enum BankCardOperation: string
{
	case AUTHORIZATION_ONLY = 'AUTHORIZATION_ONLY';
	case DEBIT = 'DEBIT';
	case AUTHORIZATION_AND_DEBIT = 'AUTHORIZATION_AND_DEBIT';
	case CREDIT = 'CREDIT';
	case CANCEL = 'CANCEL';
	case REFUND = 'REFUND';
	case REGISTER_SUBSCRIBER = 'REGISTER_SUBSCRIBER';
	case UPDATE_SUBSCRIBER = 'UPDATE_SUBSCRIBER';
	case DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER';
}